spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC
    username: root
    password: 123456
  main:
    banner-mode: off

server:
  port: 8060

mybatis-plus:
  global-config:
    banner: false